# Generated by Django 2.2.12 on 2020-08-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='grade',
        ),
        migrations.AddField(
            model_name='qualification',
            name='grades',
            field=models.TextField(default=''),
        ),
    ]
