# Generated by Django 2.2.12 on 2020-08-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20200823_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
