# Generated by Django 2.2.12 on 2020-08-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20200823_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
