# Generated by Django 2.2.12 on 2020-08-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20200823_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
